modkey = "Mod4"
workspaces = []
tags = ["", "", "", "", "", "", "", ""]

[[keybind]]
command = "Execute"
value = "dmenu_run"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "Execute"
value = "rofi -modi drun -show drun -show-icons"
modifier = ["modkey", "Mod1"]
key = "space"

[[keybind]]
command = "Execute"
value = "~/bin/rofi-locate"
modifier = ["modkey", "Mod1"]
key = "v"

[[keybind]]
command = "Execute"
value = "networkmanager_dmenu"
modifier = ["modkey", "Mod1"]
key = "n"

[[keybind]]
command = "Execute"
value = "rofi -show emoji -modi emoji"
modifier = ["modkey", "Mod1"]
key = "c"

[[keybind]]
command = "Execute"
value = "gmrun"
modifier = ["modkey", "Mod1"]
key = "p"

[[keybind]]
command = "Execute"
value = "brave"
modifier = ["modkey", "Mod1"]
key = "w"

[[keybind]]
command = "Execute"
value = "geany"
modifier = ["modkey", "Mod1"]
key = "t"

[[keybind]]
command = "Execute"
value = "pcmanfm"
modifier = ["modkey", "Mod1"]
key = "f"

[[keybind]]
command = "Execute"
value = "powerspec"
modifier = ["modkey"]
key = "x"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "Execute"
value = "pkill leftwm"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "Execute"
value = "slock"
modifier = ["modkey", "Control"]
key = "l"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey"]
key = "period"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "comma"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"

