version: "3.7"
services:
  postgresql13-server:
    image: postgres:13.1
    container_name: postgresql13-server
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=henninb
      - POSTGRES_PASSWORD=monday1
      - POSTGRES_DB=finance_db
    hostname: postgresql-server
    volumes:
      - /opt/postgresql-data:/var/lib/postgresql/data
      #      postgresql13-volume:/var/lib/postgresql/data
# volumes:
#   - postgresql13-volume:
#     driver: local
