version: "3.7"
services:
  postgresql-server:
    image: postgres:14.4
    container_name: postgresql-server
    ports:
      - "5433:5432"
    expose:
      - "5433"
    environment:
      - POSTGRES_USER=henninb
      - POSTGRES_PASSWORD=monday1
      - POSTGRES_DB=finance_db
    hostname: postgresql-server
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
      # - /opt/postgresql-data:/var/lib/postgresql/data
volumes:
  postgresql-volume:
    name: postgresql-volume
    driver: local
